#!/bin/sh
# taken from docker-wait, renamed tcp-wait
set -e
host=$1
port=$2
echo -n "waiting for TCP connection to $host:$port..."

while ! nc -w 1 $host $port 2>/dev/null
do
  echo -n .
  sleep 1
done

echo 'ok'
